replicaCount: 1

image:
  repository: vladimirkhil/sicontentservice
  pullPolicy: IfNotPresent
  tag: 1.2.0
  nginxTag: "alpine"

nginxPrometheusExporter:
  tag: 0.11.0
  port: 9113
  resources: {}

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 8080
  nginxPort: 80
  nginxTargetPort: 8088

ingress:
  enabled: false
  className: nginx
  pathType: ImplementationSpecific
  clientSecret: ''
  hosts: []
  tls: []

resources: {}
nginxResources: {}

volumePath: ''
nginxLogPath: ''

maxUploadSize: '101m'
bodyBufferSize: '10m'

options:
  maxPackageSizeMb: 100
  maxAvatarSizeMb: 1
  minDriveFreeSpaceMb: 7000
  minDriveCriticalSpaceMb: 2000
  maxPackageLifetime: '03:00:00'
  maxAvatarLifetime: '04:00:00'
  cleaningInterval: '00:30:00'
  serveStaticFiles: false
  logLevel: Warning
  otel:
    uri: 'http://localhost:4317'
    metric:
      exportInterval: 60000
