replicaCount: 1

image:
  repository: vladimirkhil/sicontentservice
  pullPolicy: IfNotPresent
  tag: 1.0.16
  nginxTag: "alpine"

nginxPrometheusExporter:
  tag: 0.11.0
  port: 9113

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  nginxPort: 80
  nginxTargetPort: 80

ingress:
  enabled: false
  clientSecret: ''
  hosts: []
  tls: []

resources: {}
nginxResources: {}

volumePath: ''
logPath: ''
nginxLogPath: ''

maxUploadSize: '101m'
bodyBufferSize: '10m'

options:
  maxPackageSizeMb: 100
  maxAvatarSizeMb: 1
  minDriveFreeSpaceMb: 7000
  minDriveCriticalSpaceMb: 2000
  maxPackageLifetime: '03:00:00'
  maxAvatarLifetime: '04:00:00'
  cleaningInterval: '00:30:00'
  serveStaticFiles: false
  logLevel: Warning
