apiVersion: v1
entries:
  sicontent:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-03-11T22:22:08.5610658+01:00"
    description: A service for uploading and retrieving SIGame content
    digest: a5cfb136e199b459d1a0404d329e3331ded50fda4473d86548984cd73add5f91
    name: sicontent
    type: application
    urls:
    - sicontent-1.0.0.tgz
    version: 1.0.0
generated: "2023-03-11T22:22:08.5490667+01:00"
