apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sicontent.fullname" . }}-nginx-configmap
  labels:
    {{- include "sicontent.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    worker_processes auto;
    worker_rlimit_nofile 131072; # added

    error_log  stderr error; # updated (notice)
    pid        /tmp/nginx.pid;

    events {
        use epoll;
        worker_connections  16384;
        multi_accept on;
    }

    http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
        
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log off; # updated
        add_header    X-Frame-Options SAMEORIGIN;

        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        on; # updated
        proxy_max_temp_file_size 0; # added
        keepalive_timeout  65;
        types_hash_max_size 2048;
        reset_timedout_connection on;
        client_header_timeout 60s; # added
        client_body_timeout 12s; # added
        server_tokens off;

        open_file_cache max=200000 inactive=20s; # added
        open_file_cache_valid 30s; # added
        open_file_cache_min_uses 2; # added
        open_file_cache_errors on; # added

        include /etc/nginx/conf.d/*.conf;
    }