apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sicontent.fullname" . }}-nginx-default-configmap
  labels:
    {{- include "sicontent.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /metrics {
            stub_status on;
            access_log off;
        }
    }