apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sicontent.fullname" . }}-secret
  labels:
    {{- include "sicontent.labels" . | nindent 4 }}
data:
  admin: {{ .Values.ingress.clientSecret | b64enc | quote }}