{
 "title": "SIContent service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uploaded packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(packages_uploaded[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Uploaded avatars",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(avatars_uploaded[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Deleted packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(packages_deleted[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Deleted avatars",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "rate(avatars_deleted[1m])", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}